global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'accounts-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'accounts-ms:8080' ]

  - job_name: 'loans-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'loans-ms:8090' ]

  - job_name: 'cards-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cards-ms:9000' ]

  - job_name: 'gatewayserver-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver-ms:8072' ]

  - job_name: 'eurekaserver-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver-ms:8070' ]

  - job_name: 'configserver-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver-ms:8071' ]
