server:
  port: 8070
spring:
  application:
    name: "eurekaserver"
# Config server address for app to contactO
  config:
    import: "optional:configserver:http://localhost:8071/"
# We dont have profiles for eureka server as props are the same
# management API endpoints are specific endpoints provided by spring and
# utilized via actuator which exposes them for use.
# One function is to perform refresh of configuration read from git post a change
# without having to restart the microservice
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
# Micrometer configuration to monitor app health
  metrics:
    logs:
      application: ${spring.application.name}

logging:
  level:
    com:
      bankeasy:
        eurekaserver: DEBUG
# log pattern for distributed tracing via open telemetry
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

